### YamlMime:ManagedReference
items:
- uid: Vintagestory.API.Client.ConfigItem
  commentId: T:Vintagestory.API.Client.ConfigItem
  id: ConfigItem
  parent: Vintagestory.API.Client
  children:
  - Vintagestory.API.Client.ConfigItem.Code
  - Vintagestory.API.Client.ConfigItem.Data
  - Vintagestory.API.Client.ConfigItem.Key
  - Vintagestory.API.Client.ConfigItem.Type
  - Vintagestory.API.Client.ConfigItem.Value
  - Vintagestory.API.Client.ConfigItem.error
  - Vintagestory.API.Client.ConfigItem.height
  - Vintagestory.API.Client.ConfigItem.posY
  langs:
  - csharp
  - vb
  name: ConfigItem
  nameWithType: ConfigItem
  fullName: Vintagestory.API.Client.ConfigItem
  type: Class
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: ConfigItem
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 16
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: A config item for the GUIElementConfigList.
  example: []
  syntax:
    content: public class ConfigItem
    content.vb: Public Class ConfigItem
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Vintagestory.API.Client.ConfigItem.Type
  commentId: F:Vintagestory.API.Client.ConfigItem.Type
  id: Type
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: ConfigItem.Type
  fullName: Vintagestory.API.Client.ConfigItem.Type
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: Type
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 21
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Item or title
  example: []
  syntax:
    content: public EnumItemType Type
    return:
      type: Vintagestory.API.Client.EnumItemType
    content.vb: Public Type As EnumItemType
- uid: Vintagestory.API.Client.ConfigItem.Key
  commentId: F:Vintagestory.API.Client.ConfigItem.Key
  id: Key
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: ConfigItem.Key
  fullName: Vintagestory.API.Client.ConfigItem.Key
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: Key
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 26
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: The name of the config item.
  example: []
  syntax:
    content: public string Key
    return:
      type: System.String
    content.vb: Public Key As String
- uid: Vintagestory.API.Client.ConfigItem.Value
  commentId: F:Vintagestory.API.Client.ConfigItem.Value
  id: Value
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: ConfigItem.Value
  fullName: Vintagestory.API.Client.ConfigItem.Value
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: Value
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 31
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: the value of the config item.
  example: []
  syntax:
    content: public string Value
    return:
      type: System.String
    content.vb: Public Value As String
- uid: Vintagestory.API.Client.ConfigItem.Code
  commentId: F:Vintagestory.API.Client.ConfigItem.Code
  id: Code
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: Code
  nameWithType: ConfigItem.Code
  fullName: Vintagestory.API.Client.ConfigItem.Code
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: Code
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 36
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: The code of the config item.
  example: []
  syntax:
    content: public string Code
    return:
      type: System.String
    content.vb: Public Code As String
- uid: Vintagestory.API.Client.ConfigItem.error
  commentId: F:Vintagestory.API.Client.ConfigItem.error
  id: error
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: error
  nameWithType: ConfigItem.error
  fullName: Vintagestory.API.Client.ConfigItem.error
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: error
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 41
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: Has this particular config item errored?
  example: []
  syntax:
    content: public bool error
    return:
      type: System.Boolean
    content.vb: Public [error] As Boolean
- uid: Vintagestory.API.Client.ConfigItem.posY
  commentId: F:Vintagestory.API.Client.ConfigItem.posY
  id: posY
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: posY
  nameWithType: ConfigItem.posY
  fullName: Vintagestory.API.Client.ConfigItem.posY
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: posY
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 46
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: The y position of the config item.
  example: []
  syntax:
    content: public double posY
    return:
      type: System.Double
    content.vb: Public posY As Double
- uid: Vintagestory.API.Client.ConfigItem.height
  commentId: F:Vintagestory.API.Client.ConfigItem.height
  id: height
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: height
  nameWithType: ConfigItem.height
  fullName: Vintagestory.API.Client.ConfigItem.height
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: height
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 51
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  summary: The height of the config item.
  example: []
  syntax:
    content: public double height
    return:
      type: System.Double
    content.vb: Public height As Double
- uid: Vintagestory.API.Client.ConfigItem.Data
  commentId: F:Vintagestory.API.Client.ConfigItem.Data
  id: Data
  parent: Vintagestory.API.Client.ConfigItem
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: ConfigItem.Data
  fullName: Vintagestory.API.Client.ConfigItem.Data
  type: Field
  source:
    remote:
      path: VintagestoryApi/Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
      branch: 9a7c32dc33877b81908edebf246419cb0681a69a
      repo: https://gitlab-ci-token:64_21Ny9stdsEkdXieYEBYX@git.striver.net/vintagecraft/game.git
    id: Data
    path: Client/UI/Elements/Impl/Interactive/GuiElementConfigList.cs
    startLine: 54
  assemblies:
  - VintagestoryAPI
  namespace: Vintagestory.API.Client
  syntax:
    content: public object Data
    return:
      type: System.Object
    content.vb: Public Data As Object
references:
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  href: Vintagestory.html
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    href: Vintagestory.html
  - name: .
  - uid: Vintagestory.API
    name: API
    href: Vintagestory.API.html
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    href: Vintagestory.API.Client.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Vintagestory.API.Client.EnumItemType
  commentId: T:Vintagestory.API.Client.EnumItemType
  parent: Vintagestory.API.Client
  href: Vintagestory.API.Client.EnumItemType.html
  name: EnumItemType
  nameWithType: EnumItemType
  fullName: Vintagestory.API.Client.EnumItemType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
